[project]
name = "bettybots"
version = "0.1.0"
description = "Flask app for Betty Bots"
readme = "README.md"
requires-python = ">=3.12"

dependencies = [
  "Flask>=3.0.0",
  "Flask-Login>=0.6.3",
  "python-dotenv>=1.0.1",
  "PyYAML>=6.0.1",
  "stripe>=10.0.0"
]

[tool.uv]
index-url = "https://pypi.org/simple"
